export enum EIcon {
	NONE='',
	ACCOUNT='ACCOUNT',
	ARROW_LEFT='ARROW_LEFT',
	ARROW_RIGHT='ARROW_RIGHT',
	CHECK='CHECK',
	CLOSE='CLOSE',
	DELETE='DELETE',
	EXCEL='EXCEL',
	EYE='EYE',
	SEARCH='SEARCH',
	SORT_ALPHABETHICAL='SORT_ALPHABETHICAL',
}